---
title: "Individual Report -- Experiment Design in CS"
header-includes:
   - \usepackage{framed}
output: pdf_document
---

## Summary
The student, individually, must write an experiment design proposal based on their 
own research topic. The general contents of the report should be as follows:

- Introduction to the research topic, and the relevant experimental questions;
- (Very Brief) review of the relevant literature;
- Experimental design (for designed experiments) or data cleaning and preconditioning (otherwise);
- Description of the data collection protocol. 
- Proposal for Statistical modeling and analysis of the data;
- Discussion of the possible results of this experiment;

Notice that in this report _it is not required of you to perform the actual experiment_. If you
have already performed some experiments (or pilot studies) related to your research, feel free 
to add them to the report, but it is not a requirement.

If you have not yet decided your research topic, feel free to use the research topic of an 
older student of your laboratory for this report. Consider the report as a source of inspiration
for your own research.

If your research topic is not experimental in nature (for example, **purely** mathematical research), please contact the professor as soon as possible in order to discuss this.

## Report
The report must be prepared using the same template as the Group Report and the case studies.
The report should contain:

- Summary;
- Introduction, including the description of the _research question_ being investigated and a brief literature review on the topic;
- Experimental design, including materials and methods, data collection protocols, criteria for including/excluding observations, etc.;
- Discussion on the **possible** results, pitfalls, and plans associated with the experiment;

The report will be evaluated according to the following criteria:

- Structure of argumentation;
- Technical correctness and methodological soundness;
- Compliance with the required format;
- Correct use of language (grammar, orthography, etc.);

## Deadline
The report should be submitted, at the latest, on the day of the final seminar. It must 
be submitted as a PDF file through MANABA.
